import { fireEvent, render, screen, within } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'

import { App } from './App'

describe('Market Copilot application shell', () => {
  beforeEach(() => {
    window.localStorage.clear()
    window.history.pushState({}, '', '/')
  })

  it('opens the market workspace as the home page', async () => {
    render(<App />)

    const cryptoHeading = await screen.findByRole('heading', { name: 'Crypto Terminal' }, { timeout: 5000 })
    expect(cryptoHeading.closest('section')?.getAttribute('data-workspace')).toBe('crypto')
    expect(screen.getByRole('navigation', { name: 'Primary navigation' })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' })).toBeTruthy()
    expect(screen.getByText('Select an instrument from Market Explorer to view scenario analysis.')).toBeTruthy()
    expect(screen.getByRole('searchbox', { name: 'Global search' })).toBeTruthy()
    expect(screen.getByRole('group', { name: 'Display mode' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'Crypto' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'Korea' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'US' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: 'Upbit' })).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    expect(within(await screen.findByRole('button', { name: 'Open BTC/KRW' })).queryByText('KRW')).toBeNull()
    expect(screen.getByText('KRW', { selector: 'button[role="tab"]' })).toBeTruthy()
    expect(screen.getByLabelText(/results$/).getAttribute('aria-live')).toBe('polite')
  })

  it('sends a selected symbol to the AI Copilot', async () => {
    render(<App />)

    fireEvent.click(await screen.findByRole('tab', { name: 'Korea' }))
    const stockHeading = await screen.findByRole('heading', { name: 'Stock Research' })
    expect(stockHeading.closest('section')?.getAttribute('data-workspace')).toBe('stock')
    expect(screen.getByText('Stock quotes are simulated. Not investment data.')).toBeTruthy()
    fireEvent.change(screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' }), { target: { value: '005930' } })
    const stockRow = await screen.findByRole('button', { name: 'Open 005930' })
    expect(within(stockRow).queryByText('KOSPI')).toBeNull()
    fireEvent.click(stockRow)

    expect(await screen.findByRole('img', { name: /005930 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect((screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' }) as HTMLInputElement).value).toBe('005930')
    expect(screen.getByRole('button', { name: 'Open 005930' })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'Trading information' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: /Samsung Electronics/i })).toBeTruthy()
    expect(screen.getByText('Market Activity')).toBeTruthy()
    expect(screen.getByText('Company research context')).toBeTruthy()
    expect(screen.getByText('Top 10 · MOCK')).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'Recent Trades' })).toBeTruthy()

    fireEvent.click(screen.getByRole('button', { name: '4H' }))
    expect(await screen.findByRole('img', { name: /005930 4H TradingView candlestick chart in mock mode/i })).toBeTruthy()

    const copilot = screen.getByRole('complementary', { name: 'AI Copilot' })
    expect(copilot.textContent).toContain('005930')
    expect(copilot.textContent).toContain('4H')
    expect(copilot.textContent).toContain('Current Price')
    expect(copilot.textContent).toContain('AI Confidence')
    expect(copilot.textContent).toContain('Scenario Analysis')
    expect(copilot.textContent).toContain('Bullish scenario')
    expect(copilot.textContent).toContain('Neutral scenario')
    expect(copilot.textContent).toContain('Bearish scenario')
    expect(copilot.textContent).toContain('Planning Reference')
    expect(copilot.textContent).toContain('Scenario Map')
    expect(copilot.textContent).toContain('Evidence Check')
    expect(copilot.textContent).toContain('AI Analysis Foundation')
    expect(copilot.textContent).toContain('Analysis Input Package')
    expect(copilot.textContent).toContain('Evidence used')
    expect(copilot.textContent).toContain('Missing evidence')
    expect(copilot.textContent).toContain('Real AI model')
    expect(copilot.textContent).toContain('Real news backend')
    expect(copilot.textContent).toContain('Real AI analysis is not connected yet')
    expect(copilot.textContent).toContain('News Evidence')
    expect(copilot.textContent).toContain('Demo news')
    expect(copilot.textContent).toContain('Demo only')
    expect(copilot.textContent).toContain('Not a buy/sell instruction')
    expect(copilot.textContent).toContain('Use with your own risk control')
    expect(copilot.textContent).toContain('Related demo news considered')
    expect(copilot.textContent).toContain('Demo news only')
    expect(copilot.textContent).toContain('Not investment advice')
    expect(copilot.textContent).toContain('Medium')
    fireEvent.change(screen.getByRole('combobox', { name: 'Language' }), { target: { value: 'ko' } })
    expect(copilot.textContent).toContain('시나리오 맵')
    expect(copilot.textContent).toContain('근거 확인')
    expect(copilot.textContent).toContain('매수·매도 지시가 아닙니다')
    expect(copilot.textContent).toContain('AI 분석 기반')
    expect(copilot.textContent).toContain('분석 입력 패키지')
    expect(copilot.textContent).toContain('실제 AI 모델')
    expect(copilot.textContent).toContain('뉴스 근거')
  })

  it('keeps an explicit mock mode for supported live markets', async () => {
    render(<App />)

    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))

    expect(await screen.findByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect(screen.getAllByText('MOCK').length).toBeGreaterThan(1)
  })

  it('keeps the active chart and copilot while browsing other markets', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))
    expect(await screen.findByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()

    fireEvent.click(screen.getByRole('tab', { name: 'Binance' }))
    expect(screen.getByRole('tab', { name: 'Binance' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    fireEvent.click(screen.getByRole('tab', { name: 'FDUSD' }))
    expect(screen.getByRole('tab', { name: 'FDUSD' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()

    fireEvent.click(screen.getByRole('tab', { name: 'Korea' }))
    expect(screen.getByRole('tab', { name: 'Korea' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('heading', { name: 'Stock Research' })).toBeTruthy()
    expect(screen.getByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect(screen.getByText(/Active analysis: BTC\/KRW/)).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' }).textContent).toContain('BTC/KRW')

    fireEvent.change(screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' }), { target: { value: '005930' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Open 005930' }))
    expect(await screen.findByRole('img', { name: /005930 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' }).textContent).toContain('005930')
    fireEvent.click(screen.getByRole('button', { name: '← All instruments' }))
    expect(screen.queryByRole('img', { name: /TradingView candlestick chart/i })).toBeNull()
    expect(screen.getByRole('tab', { name: 'Korea' }).getAttribute('aria-selected')).toBe('true')
  })

  it('switches and persists English and Korean core workspace labels', async () => {
    const app = render(<App />)
    const language = screen.getByRole('combobox', { name: 'Language' })
    fireEvent.change(language, { target: { value: 'ko' } })
    expect(screen.getByRole('link', { name: '대시보드' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: '암호화폐 터미널' })).toBeTruthy()
    expect(screen.getByRole('button', { name: /간편모드/ })).toBeTruthy()
    expect(screen.getByRole('button', { name: /전문가모드/ })).toBeTruthy()
    expect(screen.getByRole('searchbox', { name: '심볼·한국어·영어 이름 검색' })).toBeTruthy()
    expect(window.localStorage.getItem('market-copilot.language')).toBe('ko')
    app.unmount()

    render(<App />)
    expect((screen.getByRole('combobox', { name: 'Language' }) as HTMLSelectElement).value).toBe('ko')
    expect(screen.getByRole('link', { name: '대시보드' })).toBeTruthy()
    fireEvent.change(screen.getByRole('combobox', { name: 'Language' }), { target: { value: 'en' } })
    expect(screen.getByRole('heading', { name: 'Crypto Terminal' })).toBeTruthy()
    expect(screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' })).toBeTruthy()
  })

  it('filters the active venue and toggles favorites', async () => {
    render(<App />)
    fireEvent.click(await screen.findByRole('button', { name: 'MOCK' }))
    const search = screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' })
    fireEvent.change(search, { target: { value: 'XRP' } })
    expect(await screen.findByRole('button', { name: 'Open XRP/KRW' })).toBeTruthy()
    expect(screen.getByLabelText('1 results').getAttribute('aria-live')).toBe('polite')
    expect(screen.queryByRole('button', { name: 'Open BTC/KRW' })).toBeNull()

    const favoriteButton = screen.getByRole('button', { name: 'Add XRP/KRW favorite' })
    fireEvent.click(favoriteButton)
    expect(favoriteButton.getAttribute('aria-pressed')).toBe('true')
  })

  it('keeps sorting visible through search and market tab changes', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    const search = screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' })
    fireEvent.change(search, { target: { value: 'BTC' } })
    fireEvent.click(screen.getByRole('button', { name: /Sort by Price/ }))
    expect((search as HTMLInputElement).value).toBe('BTC')
    expect(screen.getByRole('status').textContent).toContain('Price ↓')
    fireEvent.click(screen.getByRole('button', { name: /Sort by Price/ }))
    expect(screen.getByRole('status').textContent).toContain('Price ↑')
    fireEvent.click(screen.getByRole('tab', { name: 'Korea' }))
    expect((search as HTMLInputElement).value).toBe('')
    expect(screen.getByRole('status').textContent).toContain('Price ↑')
    fireEvent.change(search, { target: { value: '005930' } })
    expect(await screen.findByRole('button', { name: 'Open 005930' })).toBeTruthy()
  })

  it('provides persisted multi-watchlist dashboard controls', async () => {
    window.history.pushState({}, '', '/dashboard')
    render(<App />)

    expect(await screen.findByRole('heading', { name: 'Market Radar' })).toBeTruthy()
    expect(screen.getByText(/Real AI not connected · Not investment advice/)).toBeTruthy()
    expect(await screen.findByRole('heading', { name: 'Smart Market Dashboard' })).toBeTruthy()
    expect(screen.getByRole('tab', { name: /Crypto/ })).toBeTruthy()
    expect(screen.getByRole('tab', { name: /Korea/ })).toBeTruthy()
    expect(screen.getByRole('tab', { name: /US/ })).toBeTruthy()
    expect(screen.getByRole('tab', { name: /Custom/ })).toBeTruthy()
    expect(screen.getByText('Saved locally')).toBeTruthy()

    fireEvent.click(screen.getByRole('tab', { name: /Custom/ }))
    const symbolSelect = screen.getByRole('combobox', { name: 'Symbol to add' })
    const nvidiaOption = await screen.findByRole('option', { name: /NVDA/ })
    fireEvent.change(symbolSelect, { target: { value: nvidiaOption.getAttribute('value') } })
    fireEvent.click(screen.getByRole('button', { name: 'Add symbol' }))

    expect(screen.getByRole('button', { name: 'Remove NVDA' })).toBeTruthy()
    expect(window.localStorage.getItem('investai.watchlists.v2')).toContain('us-nvda')
  })

  it('switches between crypto, Korea stock, and US stock candidate workspaces', async () => {
    window.history.pushState({}, '', '/ai-analysis')
    render(<App />)
    expect(await screen.findByRole('tab', { name: 'Crypto' })).toBeTruthy()
    fireEvent.click(screen.getByRole('tab', { name: 'Korea Stocks' }))
    expect(await screen.findByRole('heading', { name: 'Korea Stock Candidates' })).toBeTruthy()
    expect(screen.getByText(/Stock data coverage · Early beta/)).toBeTruthy()
    fireEvent.click(screen.getByRole('tab', { name: 'US Stocks' }))
    expect(await screen.findByRole('heading', { name: 'US Stock Candidates' })).toBeTruthy()
  })

  it('renders the Investor Demo route and keeps internal demo links navigable', async () => {
    window.history.pushState({}, '', '/demo')
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'Market Copilot 1.5 Beta' })).toBeTruthy()
    expect(screen.getByRole('link', { name: 'Demo' })).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: /Open Market Radar/ }))
    expect(await screen.findByRole('heading', { name: 'Market Radar' })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: '1.5 Beta scope' })).toBeTruthy()
  })

  it('keeps one global display switch across Simple and Expert routes without adding primary navigation', async () => {
    window.history.pushState({}, '', '/simple')
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'Market Copilot Simple Mode' })).toBeTruthy()
    expect(screen.queryByRole('link', { name: 'Simple' })).toBeNull()
    expect(screen.getAllByRole('group', { name: 'Display mode' })).toHaveLength(1)
    fireEvent.click(screen.getByRole('button', { name: /Simple Mode/ }))
    expect(document.querySelector('[data-display-mode]')?.getAttribute('data-display-mode')).toBe('simple')
    fireEvent.click(screen.getByRole('link', { name: 'AI Analysis' }))
    expect(await screen.findByRole('tab', { name: 'Crypto' })).toBeTruthy()
    expect(screen.getAllByRole('group', { name: 'Display mode' })).toHaveLength(1)
    expect(document.querySelector('[data-display-mode]')?.getAttribute('data-display-mode')).toBe('simple')
    expect(screen.getByRole('link', { name: 'Open Simple Candidate View' }).getAttribute('href')).toBe('/simple')
    fireEvent.click(screen.getByRole('button', { name: /Expert Mode/ }))
    expect(document.querySelector('[data-display-mode]')?.getAttribute('data-display-mode')).toBe('expert')
    expect(window.localStorage.getItem('market-copilot.displayMode.v1')).toBe('expert')
  })

  it('shows safe Simple Mode guidance across major pages while preserving their routes', async () => {
    window.history.pushState({}, '', '/dashboard')
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Simple Mode/ }))
    expect(await screen.findByText('Simple Mode shows the key market points first.')).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'Market' }))
    expect(await screen.findByText('Search a coin or stock to review the basic market context.')).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'News' }))
    expect(await screen.findByText('Start with the headline and why it may matter.')).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'Demo' }))
    expect(await screen.findByText(/Simple Mode highlights the core demo flow/)).toBeTruthy()
  })

  it('searches stocks globally and opens their market context', async () => {
    render(<App />)
    const globalSearch = screen.getByRole('searchbox', { name: 'Global search' })
    fireEvent.change(globalSearch, { target: { value: 'NVDA' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Open NVDA from global search' }))

    expect(await screen.findByRole('img', { name: /NVDA 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
  })

  it('filters the News Center by the active symbol', async () => {
    render(<App />)
    fireEvent.change(screen.getByRole('searchbox', { name: 'Global search' }), { target: { value: 'NVDA' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Open NVDA from global search' }))
    fireEvent.click(screen.getByRole('link', { name: 'News' }))

    expect(await screen.findByRole('heading', { name: 'News Center' })).toBeTruthy()
    expect(screen.getByRole('button', { name: 'NVDA ON' })).toBeTruthy()
    expect(await screen.findByRole('heading', { name: /NVIDIA outlines/ })).toBeTruthy()
    expect(screen.getAllByText('Demo news / Mock data').length).toBeGreaterThan(0)
    fireEvent.click(await within(screen.getByRole('complementary', { name: 'AI Copilot' })).findByRole('link', { name: /NVIDIA outlines/ }))
    expect((screen.getByRole('searchbox', { name: 'Search news' }) as HTMLInputElement).value).toContain('NVIDIA outlines')
    expect(screen.getByRole('button', { name: 'NVDA OFF' })).toBeTruthy()
  })

  it('opens briefing references intentionally without clearing active context on navigation', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))
    expect(await screen.findByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'Market Briefing' }))
    expect(await screen.findByRole('heading', { name: 'Market Briefing' })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' }).textContent).toContain('BTC/KRW')
    expect(screen.getAllByText('Demo briefing / Mock data').length).toBeGreaterThan(0)
    fireEvent.click(await screen.findByRole('link', { name: /Global markets assess a possible rates path/ }))
    expect(await screen.findByRole('heading', { name: 'News Center' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: /Global markets assess a possible rates path/ })).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'Market Briefing' }))
    fireEvent.click(screen.getAllByRole('button', { name: /Samsung Electronics/ })[0])
    expect(await screen.findByRole('img', { name: /005930 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' }).textContent).toContain('005930')
  })

  it('translates briefing labels and keeps mock news visibly labeled', async () => {
    window.history.pushState({}, '', '/briefing')
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'Crypto Briefing' })).toBeTruthy()
    fireEvent.change(screen.getByRole('combobox', { name: 'Language' }), { target: { value: 'ko' } })
    expect(screen.getByRole('heading', { name: '암호화폐 브리핑' })).toBeTruthy()
    expect(screen.getAllByText('데모 브리핑 / 모의 데이터').length).toBeGreaterThan(0)
    fireEvent.click(screen.getByRole('link', { name: '뉴스' }))
    expect(await screen.findByRole('heading', { name: '뉴스 센터' })).toBeTruthy()
    expect(screen.getAllByText('모의 뉴스 / 데모 데이터').length).toBeGreaterThan(0)
  })

  it('links briefing market context to a visible News filter', async () => {
    window.history.pushState({}, '', '/briefing')
    render(<App />)
    const crypto = await screen.findByRole('region', { name: 'Crypto Briefing' })
    fireEvent.click(within(crypto).getByRole('link', { name: /View market news/ }))
    expect(await screen.findByRole('heading', { name: 'News Center' })).toBeTruthy()
    expect((screen.getByRole('combobox', { name: 'Market' }) as HTMLSelectElement).value).toBe('crypto')
    expect(screen.getAllByText('Demo news / Mock data').length).toBeGreaterThan(0)
    expect(screen.getByText(/Filtered for Crypto/)).toBeTruthy()
  })

  it('combines News filters and shows an empty state without losing mock labeling', async () => {
    window.history.pushState({}, '', '/news')
    render(<App />)
    expect(await screen.findByRole('heading', { name: 'News Center' })).toBeTruthy()
    expect(await screen.findByText(/Global markets assess a possible rates path/)).toBeTruthy()
    fireEvent.click(screen.getByRole('tab', { name: 'Macro' }))
    fireEvent.change(screen.getByRole('combobox', { name: 'Market' }), { target: { value: 'macro' } })
    fireEvent.change(screen.getByRole('combobox', { name: 'Sentiment' }), { target: { value: 'negative' } })
    fireEvent.change(screen.getByRole('combobox', { name: 'Importance' }), { target: { value: 'high' } })
    expect(screen.getByText('1 ARTICLES')).toBeTruthy()
    expect(screen.getByRole('region', { name: 'Active filters' }).textContent).toContain('Macro')
    expect(screen.getByRole('button', { name: 'Remove filter: Importance High' })).toBeTruthy()
    fireEvent.change(screen.getByRole('combobox', { name: 'Importance' }), { target: { value: 'low' } })
    expect(screen.getByText('0 ARTICLES')).toBeTruthy()
    expect(screen.getByText('No articles match the active filters.')).toBeTruthy()
    expect(screen.getByText('Demo news / Mock data')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Clear all' }))
    expect(screen.queryByRole('region', { name: 'Active filters' })).toBeNull()
    expect((screen.getByRole('combobox', { name: 'Market' }) as HTMLSelectElement).value).toBe('all')
    expect((screen.getByRole('combobox', { name: 'Sentiment' }) as HTMLSelectElement).value).toBe('all')
    expect((screen.getByRole('combobox', { name: 'Importance' }) as HTMLSelectElement).value).toBe('all')
    expect(screen.queryByText('No articles match the active filters.')).toBeNull()
  })

  it('shows RSS unavailability and explicitly falls back to demo news without losing filters', async () => {
    const fetchSpy = vi.spyOn(globalThis, 'fetch').mockRejectedValue(new TypeError('Failed to fetch'))
    window.history.pushState({}, '', '/news')
    render(<App />)
    expect(await screen.findByText(/Global markets assess a possible rates path/)).toBeTruthy()
    fireEvent.change(screen.getByRole('searchbox', { name: 'Search news' }), { target: { value: 'rates' } })
    fireEvent.click(screen.getByRole('button', { name: 'RSS Experimental' }))
    expect(await screen.findByText('RSS unavailable')).toBeTruthy()
    expect(screen.getByRole('alert').textContent).toContain('Showing demo news')
    expect(window.localStorage.getItem('market-copilot.newsProviderMode')).toBe('rss-ready')
    expect((screen.getByRole('searchbox', { name: 'Search news' }) as HTMLInputElement).value).toBe('rates')
    expect(screen.getByText(/Global markets assess a possible rates path/)).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'Market Briefing' }))
    expect(await screen.findByRole('heading', { name: 'Market Briefing' })).toBeTruthy()
    expect(await screen.findByText('RSS unavailable')).toBeTruthy()
    expect(screen.getAllByText('Demo briefing / Mock data').length).toBeGreaterThan(0)
    fireEvent.click(screen.getByRole('link', { name: 'News' }))
    fireEvent.click(screen.getByRole('button', { name: 'Mock' }))
    expect(await screen.findByText('Mock', { selector: 'strong[role="status"]' })).toBeTruthy()
    expect(window.localStorage.getItem('market-copilot.newsProviderMode')).toBe('mock')
    fetchSpy.mockRestore()
  })

  it('labels a successful RSS response as real without mock article badges', async () => {
    const xml = '<rss><channel><item><title>Official rate update</title><link>https://www.federalreserve.gov/newsevents/pressreleases/example.htm</link><pubDate>Tue, 15 Sep 2026 10:00:00 GMT</pubDate><description>Policy announcement</description></item></channel></rss>'
    const fetchSpy = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(xml, { status: 200, headers: { 'Content-Type': 'text/xml' } }))
    window.localStorage.setItem('market-copilot.newsProviderMode', 'rss-ready')
    window.history.pushState({}, '', '/news')
    render(<App />)
    expect(await screen.findByText('Official rate update')).toBeTruthy()
    expect(screen.getAllByText('Real RSS News').length).toBeGreaterThan(0)
    expect(screen.queryByText('Demo news / Mock data')).toBeNull()
    expect(screen.getByText('Federal Reserve Board')).toBeTruthy()
    expect(screen.queryByRole('alert')).toBeNull()
    fetchSpy.mockRestore()
  })

  it('loads normalized real RSS through the optional local proxy mode', async () => {
    const payload = { source: 'fed-press', sourceLabel: 'Federal Reserve Board', status: 'ok', fetchedAt: '2026-09-19T00:00:00.000Z', cacheStatus: 'none', fallbackUsed: false, errors: [], articles: [{ id: 'rss-fed-press-proxy', title: 'Official proxy policy update', summary: 'Policy announcement', url: 'https://www.federalreserve.gov/newsevents/pressreleases/example.htm', publishedAt: '2026-09-18T12:00:00.000Z', source: 'Federal Reserve Board', category: 'macro', relatedMarkets: ['macro'], relatedSymbols: [], sentiment: 'unassessed', importance: 'unassessed', isMock: false }] }
    const fetchSpy = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify(payload), { status: 200, headers: { 'Content-Type': 'application/json' } }))
    window.history.pushState({}, '', '/news')
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Local Proxy Experimental' }))
    expect(await screen.findByText('Local proxy connected')).toBeTruthy()
    expect(screen.getAllByText('Real RSS loaded through local proxy').length).toBeGreaterThan(0)
    expect(screen.getByRole('heading', { name: 'Official proxy policy update' })).toBeTruthy()
    fireEvent.click(screen.getByRole('tab', { name: 'Macro' }))
    expect(screen.getByText('1 ARTICLES')).toBeTruthy()
    expect(window.localStorage.getItem('market-copilot.newsProviderMode')).toBe('local-proxy')
    fireEvent.click(screen.getByRole('link', { name: 'Market' }))
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))
    const copilot = screen.getByRole('complementary', { name: 'AI Copilot' })
    expect(copilot.textContent).toContain('News Evidence')
    expect(copilot.textContent).toContain('Local Proxy RSS')
    expect(copilot.textContent).toContain('Market-level news')
    expect(copilot.textContent).toContain('Official proxy policy update')
    expect(copilot.textContent).toContain('Local proxy prototype')
    expect(copilot.textContent).toContain('Production news backend is not connected')
    expect(copilot.textContent).not.toContain('Instrument-specific news')
    fetchSpy.mockRestore()
  })

  it('keeps the app usable and labels demo fallback when the local proxy is absent', async () => {
    const fetchSpy = vi.spyOn(globalThis, 'fetch').mockRejectedValue(new TypeError('offline'))
    window.history.pushState({}, '', '/news')
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Local Proxy Experimental' }))
    expect(await screen.findByText('Local proxy unavailable')).toBeTruthy()
    expect(screen.getByRole('alert').textContent).toContain('Local proxy unavailable. Showing demo news.')
    expect(screen.getByRole('alert').textContent).toContain('Start the local news proxy server')
    expect(screen.getByText(/Global markets assess a possible rates path/)).toBeTruthy()
    expect(screen.getAllByText('Demo news / Mock data').length).toBeGreaterThan(0)
    fetchSpy.mockRestore()
  })

  it('keeps the active instrument while reading News and changes it only on a related-symbol click', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))
    expect(await screen.findByRole('img', { name: /BTC\/KRW 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    fireEvent.click(screen.getByRole('link', { name: 'News' }))
    expect(await screen.findByRole('heading', { name: 'News Center' })).toBeTruthy()
    const copilot = screen.getByRole('complementary', { name: 'AI Copilot' })
    expect(copilot.textContent).toContain('BTC/KRW')
    fireEvent.click((await screen.findAllByRole('button', { name: 'Read details' }))[0])
    expect(copilot.textContent).toContain('BTC/KRW')
    fireEvent.click(screen.getByRole('button', { name: 'BTC/KRW ON' }))
    fireEvent.click((await screen.findAllByRole('button', { name: 'Open in Market: NVDA' }))[0])
    expect(await screen.findByRole('img', { name: /NVDA 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' }).textContent).toContain('NVDA')
    expect(screen.getByRole('heading', { name: /NVIDIA/ })).toBeTruthy()
  })

  it('updates compact instrument news and shows a no-news state for uncovered symbols', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))
    const copilot = screen.getByRole('complementary', { name: 'AI Copilot' })
    expect(await within(copilot).findByText(/Bitcoin liquidity and institutional rebalancing/)).toBeTruthy()
    fireEvent.click(screen.getByRole('tab', { name: 'Korea' }))
    fireEvent.change(screen.getByRole('searchbox', { name: 'Search symbol, Korean or English name' }), { target: { value: '035420' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Open 035420' }))
    expect(await within(copilot).findByText('No related demo news yet.')).toBeTruthy()
  })

  it('keeps a news-linked Binance symbol in its own market context', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(screen.getByRole('link', { name: 'News' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open in Market: BTCUSDT' }))
    expect(await screen.findByRole('img', { name: /BTCUSDT 1H TradingView candlestick chart in mock mode/i })).toBeTruthy()
    expect(screen.getByRole('complementary', { name: 'AI Copilot' }).textContent).toContain('binance-futures')
  })

  it('clears the Header market status after leaving Market', async () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'MOCK' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Open BTC/KRW' }))
    expect(await screen.findByTitle('Market: online')).toBeTruthy()

    fireEvent.click(screen.getByRole('link', { name: 'Dashboard' }))
    expect(await screen.findByTitle('Market: Not configured')).toBeTruthy()
  })
})
