import type { AiFeatureAccess, AiFeatureKey, AiProductTier, AiTierPolicy } from '@/types/aiProductTier'

const features: readonly AiFeatureKey[] = ['marketRadar', 'cryptoWatchCandidates', 'candidatePlanningZones', 'localNotes', 'newsOriginal', 'newsInsight', 'aiNewsSummary', 'aiCandidateAnalysis', 'candidateReport', 'aiDeepDive', 'sectorWatchCandidates', 'portfolioAnalysis', 'translationSummary', 'aiAlerts']
const policyFeatures = (overrides: Partial<Record<AiFeatureKey, AiFeatureAccess>>): Readonly<Record<AiFeatureKey, AiFeatureAccess>> => Object.fromEntries(features.map((feature) => [feature, overrides[feature] ?? 'locked'])) as Record<AiFeatureKey, AiFeatureAccess>

export const aiTierPolicies: Readonly<Record<AiProductTier, AiTierPolicy>> = {
  free: { tier: 'free', label: 'Free', monthlyPricePlaceholder: '₩0', monthlyCredits: 0, dailySoftLimit: 0, features: policyFeatures({ marketRadar: 'available', cryptoWatchCandidates: 'available', candidatePlanningZones: 'available', localNotes: 'available', newsOriginal: 'available', newsInsight: 'available', aiNewsSummary: 'locked', aiCandidateAnalysis: 'locked', candidateReport: 'locked', aiDeepDive: 'locked', sectorWatchCandidates: 'planned', portfolioAnalysis: 'planned', translationSummary: 'locked', aiAlerts: 'planned' }), description: 'Rule-based research tools and original evidence without model usage.', disclaimer: 'Planning policy only. No billing, entitlement, or AI service is active.' },
  basic: { tier: 'basic', label: 'Basic', monthlyPricePlaceholder: '₩29,000 · TBD', monthlyCredits: 50, dailySoftLimit: 5, features: policyFeatures({ marketRadar: 'available', cryptoWatchCandidates: 'available', candidatePlanningZones: 'available', localNotes: 'available', newsOriginal: 'available', newsInsight: 'available', aiNewsSummary: 'limited', aiCandidateAnalysis: 'limited', candidateReport: 'limited', translationSummary: 'limited', aiDeepDive: 'locked', sectorWatchCandidates: 'planned', portfolioAnalysis: 'planned', aiAlerts: 'planned' }), description: 'Future limited evidence summaries and candidate explanations.', disclaimer: 'Price and credits are placeholders. No payment is processed.' },
  pro: { tier: 'pro', label: 'Pro', monthlyPricePlaceholder: '₩79,000 · TBD', monthlyCredits: 200, dailySoftLimit: 20, features: policyFeatures({ marketRadar: 'available', cryptoWatchCandidates: 'available', candidatePlanningZones: 'available', localNotes: 'available', newsOriginal: 'available', newsInsight: 'available', aiNewsSummary: 'limited', aiCandidateAnalysis: 'limited', candidateReport: 'limited', aiDeepDive: 'limited', sectorWatchCandidates: 'planned', portfolioAnalysis: 'planned', translationSummary: 'limited', aiAlerts: 'planned' }), description: 'Future deeper reports with higher controlled usage limits.', disclaimer: 'Price and credits are placeholders. No payment is processed.' },
}

export const getAiTierPolicy = (tier: AiProductTier): AiTierPolicy => aiTierPolicies[tier]
