import type { MarketGroup, MarketVenue } from '@/types/market'

/** Translation-ready identifiers; language switching is intentionally out of scope. */
export const marketExplorerText = {
  en: {
    title: 'Market Explorer',
    eyebrow: 'INVESTAI / MARKET DATA',
    subtitle: 'Discover every available crypto pair and explore stock universes.',
    marketGroup: 'Market group',
    cryptoProvider: 'Crypto provider',
    marketVenue: 'Market venue',
    instrument: 'Instrument',
    instruments: 'instruments',
    open: 'Open',
    addFavorite: 'Add',
    removeFavorite: 'Remove',
    favorite: 'favorite',
    search: 'Search symbol, Korean or English name',
    favorites: 'Favorites',
    all: 'All instruments',
    results: 'results',
    price: 'Price',
    change: '24H Change',
    volume: 'Volume',
    alphabet: 'Alphabet',
    sort: 'Sort',
    ascending: 'Ascending',
    descending: 'Descending',
    loading: 'Loading market catalog…',
    retry: 'Retry',
    empty: 'No instruments match this market search.',
    live: 'LIVE CATALOG',
    mock: 'MOCK CATALOG',
    mockDisclosure: 'Stock quotes are simulated. Not investment data.',
    sourceUnavailable: 'The public market catalog is unavailable. Retry or switch to MOCK.',
    group: { crypto: 'Crypto', korea: 'Korea', us: 'US' },
    venue: {
      'upbit-krw': 'Upbit · KRW',
      'upbit-btc': 'Upbit · BTC',
      'upbit-usdt': 'Upbit · USDT',
      'binance-spot': 'Binance · Spot',
      'binance-futures': 'Binance · Futures',
      kospi: 'KOSPI',
      kosdaq: 'KOSDAQ',
      nasdaq: 'NASDAQ',
      nyse: 'NYSE',
    },
  },
  ko: {
    title: '마켓 탐색',
    eyebrow: 'INVESTAI / 마켓 데이터',
    subtitle: '거래 가능한 암호화폐와 주식 종목을 탐색합니다.',
    marketGroup: '마켓 종류',
    cryptoProvider: '암호화폐 거래소',
    marketVenue: '거래 시장',
    instrument: '종목',
    instruments: '종목',
    open: '열기',
    addFavorite: '추가',
    removeFavorite: '제거',
    favorite: '즐겨찾기',
    search: '심볼·한국어·영어 이름 검색',
    favorites: '즐겨찾기',
    all: '전체 종목',
    results: '개 결과',
    price: '현재가',
    change: '24시간 변동',
    volume: '거래량',
    alphabet: '가나다/알파벳',
    sort: '정렬',
    ascending: '오름차순',
    descending: '내림차순',
    loading: '마켓 목록을 불러오는 중…',
    retry: '재시도',
    empty: '현재 마켓에서 일치하는 종목이 없습니다.',
    live: '실시간 목록',
    mock: '모의 목록',
    mockDisclosure: '주식 시세는 모의값이며 투자 자료가 아닙니다.',
    sourceUnavailable: '공개 마켓 목록을 불러오지 못했습니다. 재시도하거나 MOCK으로 전환하세요.',
    group: { crypto: '암호화폐', korea: '한국', us: '미국' },
    venue: {
      'upbit-krw': '업비트 · KRW',
      'upbit-btc': '업비트 · BTC',
      'upbit-usdt': '업비트 · USDT',
      'binance-spot': '바이낸스 · 현물',
      'binance-futures': '바이낸스 · 선물',
      kospi: '코스피',
      kosdaq: '코스닥',
      nasdaq: '나스닥',
      nyse: '뉴욕증권거래소',
    },
  },
} as const

export const venuesByGroup: Record<MarketGroup, readonly MarketVenue[]> = {
  crypto: ['upbit-krw', 'upbit-btc', 'upbit-usdt', 'binance-spot', 'binance-futures'],
  korea: ['kospi', 'kosdaq'],
  us: ['nasdaq', 'nyse'],
}

export function groupForVenue(venue: MarketVenue): MarketGroup {
  if (venue.startsWith('upbit-') || venue.startsWith('binance-')) return 'crypto'
  return venue === 'kospi' || venue === 'kosdaq' ? 'korea' : 'us'
}
